trigger:
  branches:
    include:
    - main
    - v1.x
    - release/v1.x
    - release/v2.x
    - release/v3.x
    - release/v4.x
    - release/v3.x-preview
    - release/v4.x-preview

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng