trigger:
  branches:
    include:
    - main
    - main-preview
    - main-v2
    - main-v3
    - release/v4.x
    - release/v3.x
    - release/v2.x
    - release/v4.x-preview

  tags:
    include:
    - 'v*'

schedules:
# Ensure we build nightly to catch any new CVEs and report SDL often.
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
    - main
    - main-preview
  always: true

# CI only, does not trigger on PRs.
pr: none

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: /ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows    stages:
    - stage: RunUnitTests
      dependsOn: []

      jobs:
      - template: eng/ci/templates/jobs/run-unit-test.yml@self
        parameters:
          official: true
    
    - stage: Build
      dependsOn: []
      jobs:
      - template: eng/ci/templates/jobs/build.yml@self
        parameters:
          official: true

    - stage: EmulatorTests
      dependsOn: []
      # Run emulator tests for preview branches and main, but skip for release branches
      condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))

      jobs:
      - template: eng/ci/templates/jobs/emulator-tests.yml@self
        parameters:
          official: true
