trigger:
  branches:
    include:
      - main
      - main-preview
      - main-v2
      - main-v3

pr:
  branches:
    include:
      - main
      - main-preview
      - main-v2
      - main-v3

schedules:
  # Ensure we build nightly to catch any new CVEs and report SDL often.
  - cron: "0 1 * * *"
    displayName: Nightly Build
    branches:
      include:
        - main
        - main-preview
    always: true

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low
    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
      - stage: RunUnitTests
        dependsOn: []

        jobs:
          - template: eng/ci/templates/jobs/run-unit-test.yml@self

      - stage: Build
        dependsOn: []
        jobs:
          - template: eng/ci/templates/jobs/build.yml@self
            parameters:
              official: false

      - stage: EmulatorTests
        dependsOn: []

        jobs:
          - template: eng/ci/templates/jobs/emulator-tests.yml@self
            parameters:
              poolName: 1es-pool-azfunc-public
