trigger:
  branches:
    include:
    - main-v2

pr:
  branches:
    include:
    - main-v2

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
      demands:
      - Priority -equals Low

    stages:
    - stage: RunUnitTests
      dependsOn: []

      jobs:
      - template: eng/ci/templates/jobs/run-unit-test.yml@self
        parameters:
          poolName: 1es-pool-azfunc-public
    
    - stage: Build
      dependsOn: []
      jobs:
      - template: eng/ci/templates/jobs/build.yml@self
        parameters:
          official: false
          poolName: 1es-pool-azfunc-public

