trigger:
  branches:
    include:
    - main
    - release/v4.x
    - release/v4.x-preview

pr:
  branches:
    include:
    - main
    - release/v4.x
    - release/v4.x-preview

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    official: false
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: RunUnitTests
      dependsOn: []

      jobs:
      - template: eng/ci/templates/jobs/run-unit-test.yml@self
    
    - stage: Build
      dependsOn: []
      jobs:
      - template: eng/ci/templates/jobs/build.yml@self
