jobs:
- job: Build

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'run'
      arguments: 'skip DownloadManifestUtility,RunManifestUtilityLinux,RunManifestUtilityWindows'
      workingDirectory: '.\build'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\artifacts'
      Contents: '*.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'