jobs:
- job: RunUnitTests
  displayName: Run Unit Tests

  steps:
  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'
    
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      arguments: '-c Release'
      projects: |
        **/*Tests.csproj