jobs:
- job: RunUnitTests
  displayName: Run Unit Tests

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      performMultiLevelLookup: true

  - task: NuGetAuthenticate@1
    displayName: 'NuGet Authenticate'

  - task: DotNetCoreCLI@2
    displayName: 'Restore tests'
    inputs:
      command: 'restore'
      projects: 'ExtensionBundle.Tests.sln'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      arguments: '--configuration Release --no-restore'
      projects: |
        **/*Tests.csproj